export const CREATE_NEW_EVENT = 'CREATE_NEW_EVENT';
export const CREATE_NEW_EVENT_REQUEST = 'CREATE_NEW_EVENT/pending';
export const CREATE_NEW_EVENT_SUCESS = 'CREATE_NEW_EVENT/fulfilled';
export const CREATE_NEW_EVENT_FAILURE = 'CREATE_NEW_EVENT/rejected';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_REQUEST = 'GET_ALL_EVENTS/pending';
export const GET_ALL_EVENTS_SUCESS = 'GET_ALL_EVENTS/fulfilled';
export const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS/rejected';

export const GET_EVENTS_BY_USER = 'GET_EVENTS_BY_USER';
export const GET_EVENTS_BY_USER_REQUEST = 'GET_EVENTS_BY_USER/pending';
export const GET_EVENTS_BY_USER_SUCESS = 'GET_EVENTS_BY_USER/fulfilled';
export const GET_EVENTS_BY_USER_FAILURE = 'GET_EVENTS_BY_USER/rejected';

export const UPDATE_EVENT_BY_ID = 'UPDATE_EVENT_BY_ID'
export const UPDATE_EVENT_BY_ID_REQUEST = 'UPDATE_EVENT_BY_ID/pending';
export const UPDATE_EVENT_BY_ID_SUCESS = 'UPDATE_EVENT_BY_ID/fulfilled';
export const UPDATE_EVENT_BY_ID_FAILURE = 'UPDATE_EVENT_BY_ID/rejected';