export const CREATE_NEW_EVENT = 'CREATE_NEW_EVENT';
export const CREATE_NEW_EVENT_REQUEST = 'CREATE_NEW_EVENT/pending';
export const CREATE_NEW_EVENT_SUCESS = 'CREATE_NEW_EVENT/fulfilled';
export const CREATE_NEW_EVENT_FAILURE = 'CREATE_NEW_EVENT/rejected';

export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const GET_ALL_EVENTS_REQUEST = 'GET_ALL_EVENTS/pending';
export const GET_ALL_EVENTS_SUCESS = 'GET_ALL_EVENTS/fulfilled';
export const GET_ALL_EVENTS_FAILURE = 'GET_ALL_EVENTS/rejected';

export const GET_EVENTS_BY_USER = 'GET_EVENTS_BY_USER';
export const GET_EVENTS_BY_USER_REQUEST = 'GET_EVENTS_BY_USER/pending';
export const GET_EVENTS_BY_USER_SUCESS = 'GET_EVENTS_BY_USER/fulfilled';
export const GET_EVENTS_BY_USER_FAILURE = 'GET_EVENTS_BY_USER/rejected';