export const CREATE_NEW_EVENT = 'CREATE_NEW_EVENT';
export const CREATE_NEW_EVENT_REQUEST = 'CREATE_NEW_EVENT/pending';
export const CREATE_NEW_EVENT_SUCESS = 'CREATE_NEW_EVENT/fulfilled';
export const CREATE_NEW_EVENT_FAILURE = 'CREATE_NEW_EVENT/rejected';